stages:
  - dependencies
  - test
  - build-native
  - dockerize

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - node
    - build

get dependencies:
  image: quay.io/quarkus/ubi-quarkus-native-image:21.3.1-java11
  stage: dependencies
  script:
    - ./gradlew quarkusGoOffline

test-java:
  image: quay.io/quarkus/ubi-quarkus-native-image:21.3.1-java11
  stage: test
  script:
    - ./gradlew check

build-native:
  image:  quay.io/quarkus/ubi-quarkus-native-image:21.3.1-java11
  stage: build-native
  script:
    - ./gradlew buildNative
  artifacts:
    name: native-binary
    paths:
      - build/*-runner
  variables:
    JAVA_OPTS: "-Xmx4G -Dquarkus.native.native-image-xmx=3G"

test-native:
  image:  quay.io/quarkus/ubi-quarkus-native-image:21.3.1-java11
  stage: build-native
  script:
    - ./gradlew testNative

docker-native-build:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/src/main/docker/Dockerfile.native-micro
      --destination $CI_REGISTRY_IMAGE:$TAG
      --cache=true