stages:
  - test
  - build-native
  - dockerize

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - node
    - build

test-java:
  image: registry.access.redhat.com/ubi8/openjdk-11:1.11
  stage: test
  script:
    - ./gradlew check

build-native:
  image:  quay.io/quarkus/ubi-quarkus-native-image:21.3.1-java11
  stage: build-native
  script:
    - ./gradlew buildNative
  artifacts:
    name: native-binary
    paths:
      - build/*-runner

docker-native-build:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/src/main/docker
      --dockerfile $CI_PROJECT_DIR/src/main/docker/Dockerfile.native-micro
      --destination $CI_REGISTRY_IMAGE:$TAG
      --cache=true