version: '3.3'

services:

  database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: fruits
    ports:
      - '127.0.0.1:54321:5432'

  quarkus-demo:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    volumes:
      - ./docker-config:/deployments/config/
    depends_on:
      - database
    ports:
      - '127.0.0.1:8080:8080'
