version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "npm"
    directory: "/src/main/webapp"
    schedule:
      interval: "daily"
  
